### ISSUE TITLE
Search for someone to talk to by zip code returns the "location you entered is not found"

### ISSUE THREAD

**Issue by californiasteve** [radius314/yap#95] opened 2018-07-14 19:55 UTC
**Describe the bug**
When you call in and choose to talk to someone, then choose by zip code. You get the message "location you entered is not found". It then asks you to enter your zip code again and does a zip code meeting search.

**What version are you running**
latest unstable

**To Reproduce**
1. Dial (210) 880-3434 
2. Choose "someone to talk to"
3. Choose #2 and enter zip code 78133 (meetings in this zip code)

**Expected behavior**
Route to volunteers on duty

**Smartphone (please complete the following information):**
 - Device: Samsung S7 Active
 - OS: Android 8.0.0

**Additional context**

**Comment by radius314** [comment] 2018-07-14 20:22
What's your webhook?

**Comment by radius314** [comment] 2018-07-14 21:06
Ok I know what the issue is.  Has to do with some older functionality, which required that the "helpline" field had a value.  I need to work out a bug fix for this.

**Comment by radius314** [comment] 2018-07-14 21:13
fix pushed to latest unstable

**Comment by californiasteve** [comment] 2018-07-14 21:31
Tested and working as expected

**Closed** 2018-07-14 21:32 UTC
Labels: bug, testing, v2
