### ISSUE TITLE
voicemail

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/yap#43] opened 2018-03-16 20:59 UTC
maybe put this down the road or on horizen. thinking that I may be asked this at some point either by port city/south coastal or new england. could be nice if for some reason it cycles through and no helpline volunteer picks up it gos to a voicemail, that would then notify the helpline volunteer chair either by txt, email or both. with a link to were the voicemail file resides. maybe a super basic web interface.

**Comment by radius314** [comment] 2018-03-16 21:01
this is do-able

**Comment by pjaudiomv** [comment] 2018-03-16 21:05
cool if i do get asked ill tell them that, the south coastal area directed PR to go ahead with new phoneline, just set up a twilio for them and as they have no website, and port citys website is squarespace i will be sitting their yap on the crna.org

**Comment by radius314** [comment] 2018-07-07 03:29
this is implemented in yap 2.0, latest `unstable`.  It does not include notifications however.  That will be a separate set of changes.

**Comment by radius314** [comment] 2018-07-07 03:39
you can listen to the recordings from within the twilio console as well

https://www.twilio.com/console/voice/recordings/recording-logs

**Comment by pjaudiomv** [comment] 2018-07-07 03:55
cool this worked!! I did get a Schema validation warning 'Element 'Record' must have no character or element information item [children]' on line 11

**Comment by radius314** [comment] 2018-07-07 03:56
ok, i'm sort of opposed to implementing emailing in this right now.  i'm going to set up an SMS notification to the helpline chair route.

**Comment by radius314** [comment] 2018-07-07 03:57
and i know what the issue is with the warning

**Comment by radius314** [comment] 2018-07-07 03:59
pushed a fix

**Comment by pjaudiomv** [comment] 2018-07-07 04:02
yea as far as instant notification an sms is probably more ideal for now anyway

**Comment by radius314** [comment] 2018-07-07 05:00
notifications implemented, you will see a new option in the service body configuration for a primary contact number

**Comment by pjaudiomv** [comment] 2018-07-07 18:48
Tested this with notifications and working fine as well

**Closed** 2018-07-19 17:42 UTC
Labels: enhancement, helpline, testing, v2
