### ISSUE TITLE
server timeouts

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/yap#22] opened 2018-02-19 04:10 UTC
ive been getting server timeouts, that i havent had before. maybe ill try a different server and see if it continues there.

Twilio Error - 11205
HTTP Connection Failure - Read timed out

Msg
	HTTP Connection Failure - Read timed out
msg
	HTTP Connection Failure - Read timed out
sourceComponent
	13700
ErrorCode
	11205
LogLevel
	ERROR
url
	meeting-search.php?SearchType=1&Latitude=41.363871&Longitude=-70.5502916

PHP LOG
[Sun Feb 18 21:15:36.057637 2018] [:warn] [pid 50540] [client 184.72.115.45:35602] Timeout waiting for output from CGI script /home/nercna87/wp/yap/meeting-search.php, referer: https://wp.nerna.org/yap/address-lookup.php?Address=02539&msg=Gather+End&Called=%2B16176487329&Digits=1&ToState=MA&CallerCountry=US&Direction=inbound&CallerState=MA&ToZip=02476&CallSid=CAe852c69f9e4853af3c21f06266018427&To=%2B16176487329&CallerZip=02539&ToCountry=US&ApiVersion=2010-04-01&CalledZip=02476&CalledCity=BOSTON&CallStatus=in-progress&From=%2B15089391663&AccountSid=AC34340e47ff9bcc2aa50165a7dde3ac68&CalledCountry=US&CallerCity=EDGARTOWN&Caller=%2B15089391663&FromCountry=US&ToCity=BOSTON&FromCity=EDGARTOWN&CalledState=MA&FromZip=02539&FromState=MA

SERVER LOG
52.91.155.70 - - [18/Feb/2018:21:15:36 -0600] "GET /yap/index.php?Called=%2B16176487329&ToState=MA&CallerCountry=US&Direction=inbound&CallerState=MA&ToZip=02476&CallSid=CAd6c707e5780c8654dcd9e95d4d468189&To=%2B16176487329&CallerZip=02539&ToCountry=US&ApiVersion=2010-04-01&CalledZip=02476&CalledCity=BOSTON&CallStatus=ringing&From=%2B15089391663&AccountSid=AC34340e47ff9bcc2aa50165a7dde3ac68&CalledCountry=US&CallerCity=EDGARTOWN&Caller=%2B15089391663&FromCountry=US&ToCity=BOSTON&FromCity=EDGARTOWN&CalledState=MA&FromZip=02539&FromState=MA HTTP/1.0" 200 418 "-" "TwilioProxy/1.1"
52.202.3.1 - - [18/Feb/2018:21:15:47 -0600] "GET /yap/input-method.php?msg=Gather+End&Called=%2B16176487329&Digits=2&ToState=MA&CallerCountry=US&Direction=inbound&CallerState=MA&ToZip=02476&CallSid=CAd6c707e5780c8654dcd9e95d4d468189&To=%2B16176487329&CallerZip=02539&ToCountry=US&ApiVersion=2010-04-01&CalledZip=02476&CalledCity=BOSTON&CallStatus=in-progress&From=%2B15089391663&AccountSid=AC34340e47ff9bcc2aa50165a7dde3ac68&CalledCountry=US&CallerCity=EDGARTOWN&Caller=%2B15089391663&FromCountry=US&ToCity=BOSTON&FromCity=EDGARTOWN&CalledState=MA&FromZip=02539&FromState=MA HTTP/1.0" 200 369 "https://wp.nerna.org/yap/index.php?Called=%2B16176487329&ToState=MA&CallerCountry=US&Direction=inbound&CallerState=MA&ToZip=02476&CallSid=CAd6c707e5780c8654dcd9e95d4d468189&To=%2B16176487329&CallerZip=02539&ToCountry=US&ApiVersion=2010-04-01&CalledZip=02476&CalledCity=BOSTON&CallStatus=ringing&From=%2B15089391663&AccountSid=AC34340e47ff9bcc2aa50165a7dde3ac68&CalledCountry=US&CallerCity=EDGARTOWN&Caller=%2B15089391663&FromCountry=US&ToCity=BOSTON&FromCity=EDGARTOWN&CalledState=MA&FromZip=02539&FromState=MA" "TwilioProxy/1.1"

**Comment by radius314** [comment] 2018-02-19 04:17
which BMLT root server are you pointing to?

**Comment by pjaudiomv** [comment] 2018-02-19 04:43
wp.nerna.org/main_server/

**Comment by radius314** [comment] 2018-02-19 05:14
cannot reproduce the timeout locally.  seems intermittent.

**Comment by radius314** [comment] 2018-02-25 04:29
thinking of adding a retry mechanism, to better insulate again these types of happenings.

**Comment by radius314** [comment] 2018-03-18 05:42
closing this for now, let me know if it resurfaces

**Closed by radius314** 2018-03-18 05:42 UTC
Labels: bug

**Comment by pjaudiomv** [comment] 2018-03-18 05:51
sounds good haven't had a problem in a couple weeks now
